spring:
  application:
    name: jpaservice
  datasource:
    url: jdbc:mysql://localhost:3306/employees?useSSL=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
server:
  port: 8080