version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis-headless
    hostname: redis-headless
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
#      - ./db/initdb.d:/docker-entrypoint-initdb.d